# Generated by Django 5.2.4 on 2025-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_user_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('manager', 'Manager')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='33A34A', max_length=8),
        ),
        migrations.DeleteModel(
            name='LicenceCode',
        ),
    ]
