# Generated by Django 5.2.4 on 2025-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_user_role_alter_user_unique_id_delete_licencecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='D2E889', max_length=8),
        ),
    ]
