# Generated by Django 5.2.4 on 2025-08-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_user_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('admin', 'Admin'), ('seller', 'Seller')], default='buyer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='F175E2', max_length=8),
        ),
    ]
