# Generated by Django 4.1 on 2025-08-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_user_profile_image_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='CAF865', max_length=8),
        ),
    ]
