# Generated by Django 4.2 on 2025-08-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_ipadress_alter_user_unique_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IpAdress',
            new_name='IpAddress',
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='1D5A27', max_length=8),
        ),
    ]
