# Generated by Django 4.2 on 2025-08-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_rename_ipadress_ipaddress_alter_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='71A50C', max_length=8),
        ),
    ]
