# Generated by Django 4.2 on 2025-08-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='00BDC4', max_length=8),
        ),
    ]
