# Generated by Django 4.2 on 2025-08-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='3220A4', max_length=8),
        ),
    ]
