# Generated by Django 4.2 on 2025-08-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='query',
            new_name='query_type',
        ),
    ]
