# Generated by Django 4.2 on 2025-08-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_query_supportticket_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='3085F3', max_length=8),
        ),
    ]
