# Generated by Django 4.2 on 2025-08-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_supportticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='reason',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='6FEC40', max_length=8),
        ),
    ]
