# Generated by Django 4.2 on 2025-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_supportticket_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='EE364B', max_length=8),
        ),
    ]
