# Generated by Django 4.2 on 2025-08-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_supportticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='AF8D97', max_length=8),
        ),
    ]
