# Generated by Django 4.2 on 2025-08-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_alter_supportticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='6F8E91', max_length=8),
        ),
    ]
