# Generated by Django 4.2 on 2025-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_alter_supportticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('inprogress', 'Inprogress'), ('close', 'Close')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='C95AA5', max_length=8),
        ),
    ]
