# Generated by Django 4.2 on 2025-08-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_alter_supportticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='986EC3', max_length=8),
        ),
    ]
