# Generated by Django 4.2 on 2025-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_alter_supportticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='12DDF6', max_length=8),
        ),
    ]
