# Generated by Django 4.2 on 2025-08-11 12:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotification',
            old_name='seen',
            new_name='is_seen',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='to_all',
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('user', 'notification')},
        ),
    ]
