# Generated by Django 4.2 on 2025-08-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_seen_usernotification_is_seen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotification',
            old_name='is_seen',
            new_name='seen',
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_all',
            field=models.BooleanField(default=False),
        ),
    ]
