# Generated by Django 4.2 on 2025-08-12 05:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_rename_is_seen_usernotification_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to_all',
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('user', 'notification')},
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='seen_at',
        ),
    ]
