# Generated by Django 4.2 on 2025-08-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_to_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
